version: "3.9"

# services
services:
  # mysql container
  mysql:
    container_name: mysql
    image: mysql:8.0.35
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD test -e 'select 1'"
      interval: 1m
      timeout: 10m
      retries: 3
    networks:
      sksolutions:

  # payment backend service container
  payment:
    container_name: payment
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PWD=password
    networks:
      sksolutions:

# network
networks:
  sksolutions: