# live environment configurations
## servlet configuration
server:
  servlet:
    context-path: /sk-solutions
  port: 8081

## application configuration
spring:
  application:
    name: sk-solutions-payments
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/paymentdb?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:sksolutionstest}
    password: ${MYSQL_PWD:vq9myYHAqYuOusL}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# cors configuration
accessControl:
  allowedOrigin: ${ALLOWED_ORIGIN:*}
  allowedMethods: ${ALLOWED_METHODS:GET, POST, PUT, PATCH, DELETE, OPTIONS}
  maxAge: ${MAX_AGE:3600}
  allowedHeaders: ${ALLOWED_HEADERS:*}

## ipay payment configurations
payment:
  ipg:
    url: https://ipay.lk/ipg/checkout
    token: eyJhbGciOiJIUzUxMiJ9.eyJtaWQiOiIwMDA1MzI3MCJ9.4Jg6sXFF7z2UJmv19fqJrlqflqQwNjQYvY8vYGEg2Xd-MoSu0TFN6KzlAdthVQZ-eVmpvcK8UZ3xbQ_Id86wIQ
    secret: C29ZeekkNK89dfsuzXgu#
    schemes: Visa,MasterCard,iPay,LankaQR
    redirect-uri:
      return: http://domain:port/return?orderId=
      cancel: http://domain:port/cancel?orderId=
